[package]
name = "rustgzip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstream-io = "1.6.0"
clap = { version = "4.3.10", features = ["derive"] }
crc32fast = "1.3.2"
lazy_static = "1.4.0"
